apiVersion: batch/v1
kind: Job
metadata:
  name: cobert-dataset
spec:
  backoffLimit: 0
  template:
    spec:
      priorityClassName: research-med
      containers:
        - name: cobert-dataset-n5
          image: ls6-staff-registry.informatik.uni-wuerzburg.de/koopmann/cobert-dataset:latest
          resources:
            limits:
              cpu: "2"
              nvidia.com/gpu: "1"
              memory: "150Gi"
            requests:
              cpu: "2"
              nvidia.com/gpu: "1"
              memory: "150Gi"
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: "/workspace/data"
              name: home
          env:
            - name: HOME
              value: "/workspace/"
          command: ["/bin/bash",  "-c", "python3 -u create_temporal_dataset.py"]
      restartPolicy: Never
      imagePullSecrets:
        - name: ls6-staff-registry
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16
              - 132.187.14.17
              - 132.187.14.19
              - 132.187.14.20
            user: koopmann
            path: "/home/ls6/koopmann/code-2020-bert4coauthorrec/data/"
            secretRef:
              name: ceph-secret