apiVersion: batch/v1
kind: Job
metadata:
  name: cobert-{{ model }}-{{ dataset }}-{{ task }}
spec:
  backoffLimit: 0
  template:
    spec:
#       nodeSelector:
#         gputype: rtx8000
      priorityClassName: research-med
      containers:
        - name: cobert-{{ model }}
          image: ls6-staff-registry.informatik.uni-wuerzburg.de/koopmann/cobert-{{ model }}:latest
          resources:
            limits:
              cpu: "2"
              nvidia.com/gpu: "1"
              memory: "32Gi"
            requests:
              cpu: "2"
              nvidia.com/gpu: "1"
              memory: "32Gi"
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: "/workspace"
              name: home
              subPath: "cobert"
          workingDir: /workspace/
          env:
            - name: PYTHONPATH
              value: "/workspace/"
            - name: HOME
              value: "/tmp"
            - name: WANDB_API_KEY
              value: 1d2b0639eb5ed8f5e9126820528b5f570e997b94
            - name: WANDB_NAME
              value: cobert-{{ model }}-{{ dataset }}-{{ task }}
            - name: WANDB_PROJECT
              value: COBERT
            - name: WANDB_TAGS
              value: "{{ tags }}"
#             - name: WANDB_BASE_URL
#                 value: "http://wandb-service:8080"
          command: ["/bin/bash",  "-c", "python3 -u -m debugpy --listen 0.0.0.0:4444 run.py {% for config in configs%} --{{config.key}} {% if config.value != 'True' %}{{config.value}}{% endif %}{% endfor %}"]
#           command: ["/bin/bash",  "-c", "python3 -u run.py {% for config in configs%} --{{config.key}} {% if config.value != 'True' %}{{config.value}}{% endif %}{% endfor %}"]
      restartPolicy: Never
      imagePullSecrets:
        - name: ls6-staff-registry
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16
              - 132.187.14.17
              - 132.187.14.19
              - 132.187.14.20
            user: koopmann
            path: "/home/ls6/koopmann/"
            secretRef:
              name: ceph-secret